# --- Etapa 1: Dependencias (Deps) ---
# Usamos una imagen de Node ligera
FROM node:20-alpine AS deps
WORKDIR /app

# Copiamos solo los archivos de dependencias para aprovechar la caché
COPY package.json package-lock.json* ./
# Instalamos limpiamente las dependencias
RUN npm ci

# --- Etapa 2: Constructor (Builder) ---
FROM node:20-alpine AS builder
WORKDIR /app
# Traemos las dependencias de la etapa anterior (Rúbrica: Multi-stage build)
COPY --from=deps /app/node_modules ./node_modules
# Copiamos todo el código fuente del frontend
COPY . .
# Compilamos el proyecto Next.js para producción
RUN npm run build

# --- Etapa 3: Producción (Runner) ---
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV production

# Rúbrica: Configurar un usuario sin privilegios (no root)
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copiamos ÚNICAMENTE los archivos necesarios para correr en producción
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Cambiamos al usuario seguro
USER nextjs

# Documentamos el puerto que usa Next.js por defecto
EXPOSE 3000
ENV PORT 3000

# Comando de inicio
CMD ["npm", "start"]